server:
  port: 8888

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka:8761/eureka

spring:
  application:
    name: ApiGateWay
  cloud:
    gateway:
      routes:
      - id: userService
        uri: lb://USERSERVICE
        predicates:
        - Path=/userservice/**
      # - id: itemService
      #   uri: lb://ITEMSERVICE
      #   predicates:
      #   - Path=/itemservice/**
      # - id: transactionService
      #   uri: lb://TRANSACTIONSERVICE
      #   predicates:
      #   - Path=/transactionservice/**
      # #socketserver
      # - id: socketserver
      #   uri: lb://socketserver
      #   predicates:
      #   - Path=/socketserver/**